// Semantic response cache.
//
// Perimenopause questions cluster hard — a few thousand distinct phrasings
// cover the forty symptoms — so most turns can be answered from a previous
// generation instead of a fresh model call.
//
// The index lives in memory as one flat Float32Array: 512 dims x 4 bytes is
// 2 KB per entry, so ~10k cached questions is ~20 MB and a full scan is a few
// million multiply-adds (single-digit milliseconds). Postgres is the durable
// store that repopulates the index on boot; vectors are never queried in SQL,
// so no pgvector extension is required.

import { prisma } from '@anuva/database';
import { EMBED_DIMENSIONS } from './openai.js';
import { PROMPT_VERSION } from './prompt.js';

// Read lazily — see the note in openai.ts: .env is loaded in the body of
// index.ts, which runs after this module has already been imported.
//
// The threshold is deliberately tight. A near-miss hit serves a clinically
// wrong answer with cache confidence, which is worse than paying for another
// model call, so err toward missing. Raise, never lower, without an eval.
//
// Raised 0.94 -> 0.97 with the v13 prompt. At 0.94 the paraphrases of a first
// message ("I feel tired", "I'm exhausted all the time", "no energy at all")
// scored above the line and were answered from each other, so the one turn that
// most needs to sound like a reply to HER was the turn most likely to be someone
// else's stored wording. Only opening messages are cacheable at all (see
// isCacheable in engine.ts), which is exactly that turn — so this path was
// carrying the "generic reply" complaint on its own.
//
// The cost is hit rate, paid in completions, not in correctness. Retune it from
// the `similarity` column on AnuChatTurn once there is v13 traffic in there:
// those are real near-miss scores, which is better evidence than this number is.
const similarityThreshold = () => Number(process.env.ANU_CACHE_THRESHOLD || 0.97);
const maxEntries = () => Number(process.env.ANU_CACHE_MAX_ENTRIES || 20000);
/// Workers each hold their own copy, so a reply generated by one is invisible
/// to the others until the next refresh.
const refreshIntervalMs = () => Number(process.env.ANU_CACHE_REFRESH_MS || 120000);

type Entry = { id: string; reply: string; suggestions: string[]; symptom: string | null };

let vectors = new Float32Array(0);
let entries: Entry[] = [];
let loaded = false;
let lastLoadedAt = 0;

function toBuffer(vec: Float32Array): Uint8Array<ArrayBuffer> {
  const out = new Uint8Array(new ArrayBuffer(vec.byteLength));
  out.set(new Uint8Array(vec.buffer, vec.byteOffset, vec.byteLength));
  return out;
}

function fromBuffer(buf: Uint8Array): Float32Array | null {
  if (buf.byteLength !== EMBED_DIMENSIONS * 4) return null;
  // Copy rather than view — the row buffer is not guaranteed to be aligned.
  const out = new Float32Array(EMBED_DIMENSIONS);
  const view = new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
  for (let i = 0; i < EMBED_DIMENSIONS; i += 1) out[i] = view.getFloat32(i * 4, true);
  return out;
}

/// Loads every cache row for the current prompt version into the in-memory
/// index. Rows written by an older prompt are left behind, so a prompt edit
/// retires its cached wording automatically.
export async function loadCache(): Promise<number> {
  const rows = await prisma.anuResponseCache.findMany({
    where: { promptVersion: PROMPT_VERSION },
    select: { id: true, reply: true, suggestions: true, symptom: true, embedding: true },
    orderBy: { lastUsedAt: 'desc' },
    take: maxEntries(),
  });

  const nextVectors = new Float32Array(rows.length * EMBED_DIMENSIONS);
  const nextEntries: Entry[] = [];
  for (const row of rows) {
    const vec = fromBuffer(row.embedding);
    if (!vec) continue;
    nextVectors.set(vec, nextEntries.length * EMBED_DIMENSIONS);
    nextEntries.push({
      id: row.id,
      reply: row.reply,
      suggestions: row.suggestions,
      symptom: row.symptom,
    });
  }

  vectors = nextVectors;
  entries = nextEntries;
  loaded = true;
  lastLoadedAt = Date.now();
  return entries.length;
}

async function ensureLoaded(): Promise<void> {
  if (!loaded || Date.now() - lastLoadedAt > refreshIntervalMs()) {
    await loadCache();
  }
}

export type CacheHit = {
  id: string;
  reply: string;
  suggestions: string[];
  symptom: string | null;
  similarity: number;
};
/// `bestScore` is reported even when nothing cleared the threshold, so the
/// near-misses in AnuChatTurn can be used to retune it against real traffic
/// instead of guesswork.
export type CacheLookup = { hit: CacheHit | null; bestScore: number | null };

/// Vectors are unit-normalised on the way in, so cosine similarity is a dot
/// product.
export async function lookup(embedding: Float32Array): Promise<CacheLookup> {
  await ensureLoaded();
  if (entries.length === 0) return { hit: null, bestScore: null };

  let bestIndex = -1;
  let bestScore = -Infinity;
  for (let i = 0; i < entries.length; i += 1) {
    const offset = i * EMBED_DIMENSIONS;
    let dot = 0;
    for (let d = 0; d < EMBED_DIMENSIONS; d += 1) {
      dot += (vectors[offset + d] as number) * (embedding[d] as number);
    }
    if (dot > bestScore) {
      bestScore = dot;
      bestIndex = i;
    }
  }

  const hit = bestIndex >= 0 ? entries[bestIndex] : undefined;
  const best = bestIndex >= 0 ? bestScore : null;
  if (!hit || bestScore < similarityThreshold()) return { hit: null, bestScore: best };

  // Fire-and-forget: usage stats must never delay the reply.
  void prisma.anuResponseCache
    .update({
      where: { id: hit.id },
      data: { hits: { increment: 1 }, lastUsedAt: new Date() },
    })
    .catch(() => undefined);

  return {
    hit: {
      id: hit.id,
      reply: hit.reply,
      suggestions: hit.suggestions,
      symptom: hit.symptom,
      similarity: bestScore,
    },
    bestScore: best,
  };
}

/// Persists a freshly generated reply and pushes it into the live index so the
/// next identical question in this process hits without waiting for a refresh.
export async function store(
  question: string,
  reply: string,
  suggestions: string[],
  symptom: string | null,
  embedding: Float32Array,
): Promise<void> {
  const row = await prisma.anuResponseCache.create({
    data: {
      question,
      reply,
      suggestions,
      symptom,
      embedding: toBuffer(embedding),
      promptVersion: PROMPT_VERSION,
    },
    select: { id: true },
  });

  if (entries.length >= maxEntries()) return;

  const nextVectors = new Float32Array((entries.length + 1) * EMBED_DIMENSIONS);
  nextVectors.set(vectors.subarray(0, entries.length * EMBED_DIMENSIONS), 0);
  nextVectors.set(embedding, entries.length * EMBED_DIMENSIONS);
  vectors = nextVectors;
  entries.push({ id: row.id, reply, suggestions, symptom });
}

export function cacheStats(): { size: number; loadedAt: number | null } {
  return { size: entries.length, loadedAt: loaded ? lastLoadedAt : null };
}
