import path from 'node:path';
import { fileURLToPath } from 'node:url';
import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default {
  darkMode: 'class',
  content: [path.join(__dirname, 'index.html'), path.join(__dirname, 'src/**/*.{js,ts,jsx,tsx}')],
  plugins: [forms],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#F7F0E8',
        'border-default': 'rgba(94, 53, 102, 0.15)',
        'surface-container-lowest': '#FFFFFF',
        'surface-tint': '#5E3566',
        outline: '#6E5A78',
        'secondary-fixed': '#F4DCE0',
        'on-surface-variant': '#5C4A66',
        info: '#5B82C4',
        'surface-container-high': '#ECDFD0',
        'on-tertiary-container': '#5A4716',
        'tertiary-fixed': '#F0E4C8',
        tertiary: '#B8923C',
        'primary-fixed-dim': '#CDB9DE',
        'on-tertiary-fixed': '#3A2E0E',
        error: '#C0405A',
        'on-surface': '#3E2542',
        primary: '#5E3566',
        'surface-base': '#F7F0E8',
        'secondary-container': '#F4DCE0',
        'error-container': '#F8DCE2',
        'on-primary-container': '#3E2542',
        'inverse-primary': '#CDB9DE',
        'on-secondary-container': '#7A3A4C',
        'on-primary': '#FBF6F0',
        'on-primary-fixed': '#2A0F33',
        'surface-container': '#F3E9DD',
        warning: '#C9912E',
        success: '#4F9D6B',
        'outline-variant': '#E3D4DC',
        'tertiary-container': '#F0E4C8',
        background: '#F7F0E8',
        'surface-variant': '#ECDFD0',
        'primary-fixed': '#E7DCEC',
        'on-background': '#3E2542',
        'inverse-surface': '#3E2542',
        'on-secondary': '#FFFFFF',
        'on-primary-fixed-variant': '#4F319C',
        'surface-container-low': '#FBF6F0',
        locked: '#9E8BA8',
        'surface-sunken': '#EFE4D8',
        'tertiary-fixed-dim': '#B8923C',
        'on-error-container': '#5A1020',
        'surface-overlay': '#5E3566',
        'surface-container-highest': '#ECDFD0',
        'primary-container': '#E7DCEC',
        'on-secondary-fixed': '#7A3A4C',
        'surface-raised': '#FFFFFF',
        'secondary-fixed-dim': '#C97E92',
        'on-tertiary-fixed-variant': '#5A4716',
        'deep-space': '#5E3566',
        secondary: '#C97E92',
        'surface-bright': '#FFFFFF',
        surface: '#F7F0E8',
        'on-error': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'surface-dim': '#EFE4D8',
        'on-secondary-fixed-variant': '#7A3A4C',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        body: ['Mulish', 'sans-serif'],
        display: ['Fraunces', 'serif'],
        script: ['"Dancing Script"', 'cursive'],
      },
    },
  },
} satisfies Config;
