import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  plugins: [forms],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#322f37',
        'border-default': 'rgba(167, 139, 250, 0.2)',
        'surface-container-lowest': '#0f0d14',
        'surface-tint': '#cebdff',
        outline: '#948e9d',
        'secondary-fixed': '#ffe24c',
        'on-surface-variant': '#cac4d4',
        info: '#60A5FA',
        'surface-container-high': '#2b2930',
        'on-tertiary-container': '#3b3500',
        'tertiary-fixed': '#f8e454',
        tertiary: '#dbc839',
        'primary-fixed-dim': '#cebdff',
        'on-tertiary-fixed': '#201c00',
        error: '#F87171',
        'on-surface': '#e6e0ea',
        primary: '#cebdff',
        'surface-base': '#1E1B4B',
        'secondary-container': '#c1a800',
        'error-container': '#93000a',
        'on-primary-container': '#3c1989',
        'inverse-primary': '#674bb5',
        'on-secondary-container': '#483d00',
        'on-primary': '#381385',
        'on-primary-fixed': '#21005e',
        'surface-container': '#211e25',
        warning: '#FBBF24',
        success: '#4ADE80',
        'outline-variant': '#494552',
        'tertiary-container': '#af9e00',
        background: '#141219',
        'surface-variant': '#36343b',
        'primary-fixed': '#e8ddff',
        'on-background': '#e6e0ea',
        'inverse-surface': '#e6e0ea',
        'on-secondary': '#393000',
        'on-primary-fixed-variant': '#4f319c',
        'surface-container-low': '#1d1a21',
        locked: '#8B82C3',
        'surface-sunken': '#141136',
        'tertiary-fixed-dim': '#dbc839',
        'on-error-container': '#ffdad6',
        'surface-overlay': '#3D3890',
        'surface-container-highest': '#36343b',
        'primary-container': '#a78bfa',
        'on-secondary-fixed': '#211b00',
        'surface-raised': '#2E2A6E',
        'secondary-fixed-dim': '#e2c62d',
        'on-tertiary-fixed-variant': '#504700',
        'deep-space': '#1E1B4B',
        secondary: '#e2c62d',
        'surface-bright': '#3b383f',
        surface: '#141219',
        'on-error': '#690005',
        'on-tertiary': '#373100',
        'surface-dim': '#141219',
        'on-secondary-fixed-variant': '#524600',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        /** StarChart tokens (see DESIGN.md): sm 8px, md 12px, lg 16px */
        'starchart-sm': '0.5rem',
        'starchart-md': '0.75rem',
        'starchart-lg': '1rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sp-6': '48px',
        'sp-7': '64px',
        base: '8px',
        'sp-2': '8px',
        'sp-5': '32px',
        'sp-8': '96px',
        'sp-3': '16px',
        'sp-4': '24px',
        'sp-1': '4px',
      },
      fontFamily: {
        tiny: ['Lexend', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
        body: ['Lexend', 'sans-serif'],
        h1: ['"Plus Jakarta Sans"', 'sans-serif'],
        h2: ['"Plus Jakarta Sans"', 'sans-serif'],
        small: ['Lexend', 'sans-serif'],
        h3: ['"Plus Jakarta Sans"', 'sans-serif'],
        h4: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        tiny: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        mono: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        body: ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        h1: ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['28px', { lineHeight: '1.25', fontWeight: '700' }],
        small: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        h3: ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        h4: ['18px', { lineHeight: '1.35', fontWeight: '600' }],
      },
    },
  },
} satisfies Config;
