import type { Config } from 'tailwindcss';
import forms from '@tailwindcss/forms';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  plugins: [forms],
  theme: {
    extend: {
      colors: {
        // Anuva Wellness — light, warm brand (token names unchanged; values inverted to light scheme)
        'inverse-on-surface': '#F7F0E8',
        'border-default': 'rgba(94, 53, 102, 0.15)',
        'surface-container-lowest': '#FFFFFF',
        'surface-tint': '#5E3566',
        outline: '#6E5A78',
        'secondary-fixed': '#F4DCE0',
        'on-surface-variant': '#5C4A66',
        info: '#5B82C4',
        'surface-container-high': '#ECDFD0',
        'on-tertiary-container': '#5A4716',
        'tertiary-fixed': '#F0E4C8',
        tertiary: '#B8923C',
        'primary-fixed-dim': '#CDB9DE',
        'on-tertiary-fixed': '#3A2E0E',
        error: '#C0405A',
        'on-surface': '#3E2542',
        primary: '#5E3566',
        'surface-base': '#F7F0E8',
        'secondary-container': '#F4DCE0',
        'error-container': '#F8DCE2',
        'on-primary-container': '#3E2542',
        'inverse-primary': '#CDB9DE',
        'on-secondary-container': '#7A3A4C',
        'on-primary': '#FBF6F0',
        'on-primary-fixed': '#2A0F33',
        'surface-container': '#F3E9DD',
        warning: '#C9912E',
        success: '#4F9D6B',
        'outline-variant': '#E3D4DC',
        'tertiary-container': '#F0E4C8',
        background: '#F7F0E8',
        'surface-variant': '#ECDFD0',
        'primary-fixed': '#E7DCEC',
        'on-background': '#3E2542',
        'inverse-surface': '#3E2542',
        'on-secondary': '#FFFFFF',
        'on-primary-fixed-variant': '#4F319C',
        'surface-container-low': '#FBF6F0',
        locked: '#9E8BA8',
        'surface-sunken': '#EFE4D8',
        'tertiary-fixed-dim': '#B8923C',
        'on-error-container': '#5A1020',
        'surface-overlay': '#5E3566',
        'surface-container-highest': '#ECDFD0',
        'primary-container': '#E7DCEC',
        'on-secondary-fixed': '#7A3A4C',
        'surface-raised': '#FFFFFF',
        'secondary-fixed-dim': '#C97E92',
        'on-tertiary-fixed-variant': '#5A4716',
        'deep-space': '#5E3566',
        secondary: '#C97E92',
        'surface-bright': '#FFFFFF',
        surface: '#F7F0E8',
        'on-error': '#FFFFFF',
        'on-tertiary': '#FFFFFF',
        'surface-dim': '#EFE4D8',
        'on-secondary-fixed-variant': '#7A3A4C',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        /** StarChart tokens (see DESIGN.md): sm 8px, md 12px, lg 16px */
        'starchart-sm': '0.5rem',
        'starchart-md': '0.75rem',
        'starchart-lg': '1rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'sp-6': '48px',
        'sp-7': '64px',
        base: '8px',
        'sp-2': '8px',
        'sp-5': '32px',
        'sp-8': '96px',
        'sp-3': '16px',
        'sp-4': '24px',
        'sp-1': '4px',
      },
      fontFamily: {
        tiny: ['Mulish', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
        script: ['"Dancing Script"', 'cursive'],
        body: ['Mulish', 'sans-serif'],
        h1: ['Fraunces', 'serif'],
        h2: ['Fraunces', 'serif'],
        small: ['Mulish', 'sans-serif'],
        h3: ['Fraunces', 'serif'],
        h4: ['Fraunces', 'serif'],
      },
      fontSize: {
        tiny: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
        mono: ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        body: ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        h1: ['36px', { lineHeight: '1.2', fontWeight: '700' }],
        h2: ['28px', { lineHeight: '1.25', fontWeight: '700' }],
        small: ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        h3: ['22px', { lineHeight: '1.3', fontWeight: '600' }],
        h4: ['18px', { lineHeight: '1.35', fontWeight: '600' }],
      },
    },
  },
} satisfies Config;
